-- Car Rental Management System - SQL Queries
-- PostgreSQL Implementation
-- Total: 20 Queries demonstrating variety

-- ============================================
-- SIMPLE SELECT + FILTERING/SORTING QUERIES (3 minimum)
-- ============================================

-- Query 1: List all available vehicles sorted by daily rate (ascending)
SELECT 
    vehicle_id,
    registration_number,
    make,
    model,
    year,
    color,
    daily_rate,
    status
FROM VEHICLE
WHERE status = 'Available'
ORDER BY daily_rate ASC;

-- Query 2: Find all VIP customers who registered in 2023
SELECT 
    customer_id,
    first_name,
    last_name,
    email,
    phone,
    registration_date,
    customer_type
FROM CUSTOMER
WHERE customer_type = 'VIP' 
    AND EXTRACT(YEAR FROM registration_date) = 2023
ORDER BY registration_date;

-- Query 3: List all luxury vehicles manufactured after 2023
SELECT 
    v.vehicle_id,
    v.make,
    v.model,
    v.year,
    v.color,
    v.daily_rate,
    vc.category_name
FROM VEHICLE v
JOIN VEHICLE_CATEGORY vc ON v.category_id = vc.category_id
WHERE vc.category_name = 'Luxury' 
    AND v.year > 2023
ORDER BY v.daily_rate DESC;

-- ============================================
-- AGGREGATE + GROUP BY/HAVING QUERIES (4 minimum)
-- ============================================

-- Query 4: Count total reservations by status with total revenue
SELECT 
    status,
    COUNT(*) AS total_reservations,
    SUM(total_amount) AS total_revenue,
    AVG(total_amount) AS avg_rental_cost,
    MIN(total_amount) AS min_rental_cost,
    MAX(total_amount) AS max_rental_cost
FROM RESERVATION
GROUP BY status
ORDER BY total_revenue DESC;

-- Query 5: Find vehicle categories with average daily rate above $50
SELECT 
    vc.category_name,
    COUNT(v.vehicle_id) AS vehicle_count,
    AVG(v.daily_rate) AS avg_daily_rate,
    MIN(v.daily_rate) AS min_rate,
    MAX(v.daily_rate) AS max_rate
FROM VEHICLE_CATEGORY vc
JOIN VEHICLE v ON vc.category_id = v.category_id
GROUP BY vc.category_name
HAVING AVG(v.daily_rate) > 50
ORDER BY avg_daily_rate DESC;

-- Query 6: Calculate total maintenance costs per vehicle for vehicles with costs over $500
SELECT 
    v.vehicle_id,
    v.registration_number,
    v.make,
    v.model,
    COUNT(m.maintenance_id) AS maintenance_count,
    SUM(m.cost) AS total_maintenance_cost,
    AVG(m.cost) AS avg_maintenance_cost
FROM VEHICLE v
JOIN MAINTENANCE m ON v.vehicle_id = m.vehicle_id
GROUP BY v.vehicle_id, v.registration_number, v.make, v.model
HAVING SUM(m.cost) > 500
ORDER BY total_maintenance_cost DESC;

-- Query 7: Show total revenue generated by each customer type
SELECT 
    c.customer_type,
    COUNT(DISTINCT c.customer_id) AS customer_count,
    COUNT(r.reservation_id) AS total_reservations,
    SUM(p.amount) AS total_revenue,
    AVG(p.amount) AS avg_payment
FROM CUSTOMER c
JOIN RESERVATION r ON c.customer_id = r.customer_id
JOIN PAYMENT p ON r.reservation_id = p.reservation_id
GROUP BY c.customer_type
ORDER BY total_revenue DESC;

-- ============================================
-- MULTI-TABLE JOIN QUERIES (4 minimum)
-- ============================================

-- Query 8: Show complete reservation details with customer, vehicle, and employee information
SELECT 
    r.reservation_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.email AS customer_email,
    v.make || ' ' || v.model AS vehicle,
    v.registration_number,
    vc.category_name,
    e.first_name || ' ' || e.last_name AS processed_by,
    r.pickup_date,
    r.return_date,
    r.total_amount,
    r.status
FROM RESERVATION r
JOIN CUSTOMER c ON r.customer_id = c.customer_id
JOIN VEHICLE v ON r.vehicle_id = v.vehicle_id
JOIN VEHICLE_CATEGORY vc ON v.category_id = vc.category_id
JOIN EMPLOYEE e ON r.employee_id = e.employee_id
ORDER BY r.reservation_date DESC;

-- Query 9: List all payments with associated reservation and customer details
SELECT 
    p.payment_id,
    p.transaction_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    r.reservation_id,
    v.make || ' ' || v.model AS vehicle,
    p.payment_date,
    p.amount,
    p.payment_method,
    p.payment_status,
    p.late_fee,
    p.damage_charge,
    (p.amount + p.late_fee + p.damage_charge) AS total_paid
FROM PAYMENT p
JOIN CUSTOMER c ON p.customer_id = c.customer_id
JOIN RESERVATION r ON p.reservation_id = r.reservation_id
JOIN VEHICLE v ON r.vehicle_id = v.vehicle_id
WHERE p.payment_status = 'Completed'
ORDER BY p.payment_date DESC;

-- Query 10: Show maintenance history with vehicle and employee details
SELECT 
    m.maintenance_id,
    v.registration_number,
    v.make || ' ' || v.model AS vehicle,
    vc.category_name,
    m.maintenance_type,
    m.maintenance_date,
    e.first_name || ' ' || e.last_name AS technician,
    e.department,
    m.cost,
    m.status,
    m.description
FROM MAINTENANCE m
JOIN VEHICLE v ON m.vehicle_id = v.vehicle_id
JOIN VEHICLE_CATEGORY vc ON v.category_id = vc.category_id
JOIN EMPLOYEE e ON m.employee_id = e.employee_id
WHERE m.status = 'Completed'
ORDER BY m.maintenance_date DESC;

-- Query 11: Find customers with their total spending and number of rentals
SELECT 
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.customer_type,
    COUNT(r.reservation_id) AS total_rentals,
    SUM(p.amount + p.late_fee + p.damage_charge) AS total_spent,
    AVG(p.amount) AS avg_rental_cost
FROM CUSTOMER c
JOIN RESERVATION r ON c.customer_id = r.customer_id
JOIN PAYMENT p ON r.reservation_id = p.reservation_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.customer_type
ORDER BY total_spent DESC;

-- ============================================
-- SUBQUERY QUERIES (3 minimum)
-- ============================================

-- Query 12: Find vehicles that have never been rented
SELECT 
    v.vehicle_id,
    v.registration_number,
    v.make,
    v.model,
    v.year,
    vc.category_name,
    v.daily_rate,
    v.status
FROM VEHICLE v
JOIN VEHICLE_CATEGORY vc ON v.category_id = vc.category_id
WHERE v.vehicle_id NOT IN (
    SELECT DISTINCT vehicle_id 
    FROM RESERVATION
)
ORDER BY v.daily_rate DESC;

-- Query 13: Find customers who have spent more than the average customer
SELECT 
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.email,
    c.customer_type,
    SUM(p.amount + p.late_fee + p.damage_charge) AS total_spent
FROM CUSTOMER c
JOIN RESERVATION r ON c.customer_id = r.customer_id
JOIN PAYMENT p ON r.reservation_id = p.reservation_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.email, c.customer_type
HAVING SUM(p.amount + p.late_fee + p.damage_charge) > (
    SELECT AVG(total_payment)
    FROM (
        SELECT SUM(amount + late_fee + damage_charge) AS total_payment
        FROM PAYMENT
        GROUP BY customer_id
    ) AS customer_totals
)
ORDER BY total_spent DESC;

-- Query 14: List vehicles with maintenance costs above category average
SELECT 
    v.vehicle_id,
    v.registration_number,
    v.make || ' ' || v.model AS vehicle,
    vc.category_name,
    COALESCE(SUM(m.cost), 0) AS total_maintenance_cost
FROM VEHICLE v
JOIN VEHICLE_CATEGORY vc ON v.category_id = vc.category_id
LEFT JOIN MAINTENANCE m ON v.vehicle_id = m.vehicle_id
GROUP BY v.vehicle_id, v.registration_number, v.make, v.model, vc.category_name, v.category_id
HAVING COALESCE(SUM(m.cost), 0) > (
    SELECT AVG(cat_cost)
    FROM (
        SELECT SUM(m2.cost) AS cat_cost
        FROM VEHICLE v2
        LEFT JOIN MAINTENANCE m2 ON v2.vehicle_id = m2.vehicle_id
        WHERE v2.category_id = v.category_id
        GROUP BY v2.vehicle_id
    ) AS category_costs
)
ORDER BY total_maintenance_cost DESC;

-- ============================================
-- DATE/STRING FUNCTIONS + BUSINESS QUESTIONS (3 minimum)
-- ============================================

-- Query 15: Calculate rental duration and cost efficiency for completed reservations
SELECT 
    r.reservation_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    v.make || ' ' || v.model AS vehicle,
    r.pickup_date,
    r.return_date,
    r.actual_return_date,
    (r.actual_return_date - r.pickup_date) AS actual_duration_days,
    (r.return_date - r.pickup_date) AS planned_duration_days,
    r.total_amount,
    ROUND(r.total_amount / NULLIF(r.actual_return_date - r.pickup_date, 0), 2) AS cost_per_day,
    CASE 
        WHEN r.actual_return_date > r.return_date THEN 'Late Return'
        WHEN r.actual_return_date < r.return_date THEN 'Early Return'
        ELSE 'On Time'
    END AS return_status
FROM RESERVATION r
JOIN CUSTOMER c ON r.customer_id = c.customer_id
JOIN VEHICLE v ON r.vehicle_id = v.vehicle_id
WHERE r.status = 'Completed' AND r.actual_return_date IS NOT NULL
ORDER BY r.pickup_date DESC;

-- Query 16: Find customers whose licenses expire within the next 6 months
SELECT 
    customer_id,
    first_name || ' ' || last_name AS customer_name,
    email,
    phone,
    license_number,
    license_expiry,
    (license_expiry - CURRENT_DATE) AS days_until_expiry,
    CASE 
        WHEN license_expiry - CURRENT_DATE <= 30 THEN 'Urgent'
        WHEN license_expiry - CURRENT_DATE <= 90 THEN 'Soon'
        ELSE 'Moderate'
    END AS urgency_level
FROM CUSTOMER
WHERE license_expiry <= CURRENT_DATE + INTERVAL '6 months'
ORDER BY license_expiry;

-- Query 17: Analyze monthly revenue trends
SELECT 
    TO_CHAR(p.payment_date, 'YYYY-MM') AS year_month,
    TO_CHAR(p.payment_date, 'Month YYYY') AS month_name,
    COUNT(DISTINCT p.payment_id) AS total_payments,
    COUNT(DISTINCT r.reservation_id) AS total_reservations,
    SUM(p.amount + p.late_fee + p.damage_charge) AS total_revenue,
    AVG(p.amount) AS avg_payment,
    SUM(p.late_fee) AS total_late_fees,
    SUM(p.damage_charge) AS total_damage_charges
FROM PAYMENT p
JOIN RESERVATION r ON p.reservation_id = r.reservation_id
WHERE p.payment_status = 'Completed'
GROUP BY TO_CHAR(p.payment_date, 'YYYY-MM'), TO_CHAR(p.payment_date, 'Month YYYY')
ORDER BY year_month DESC;

-- ============================================
-- ADVANCED QUERIES (Window Functions, CTEs, Correlated Subqueries)
-- ============================================

-- Query 18: Rank vehicles by total revenue generated using window functions
SELECT 
    v.vehicle_id,
    v.registration_number,
    v.make || ' ' || v.model AS vehicle,
    vc.category_name,
    COUNT(r.reservation_id) AS rental_count,
    SUM(r.total_amount) AS total_revenue,
    AVG(r.total_amount) AS avg_rental_value,
    RANK() OVER (ORDER BY SUM(r.total_amount) DESC) AS revenue_rank,
    RANK() OVER (PARTITION BY vc.category_name ORDER BY SUM(r.total_amount) DESC) AS category_rank
FROM VEHICLE v
JOIN VEHICLE_CATEGORY vc ON v.category_id = vc.category_id
LEFT JOIN RESERVATION r ON v.vehicle_id = r.vehicle_id
GROUP BY v.vehicle_id, v.registration_number, v.make, v.model, vc.category_name
ORDER BY total_revenue DESC NULLS LAST;

-- Query 19: Use CTE to find employee performance metrics
WITH EmployeeStats AS (
    SELECT 
        e.employee_id,
        e.first_name || ' ' || e.last_name AS employee_name,
        e.department,
        e.position,
        COUNT(DISTINCT r.reservation_id) AS reservations_processed,
        COALESCE(SUM(r.total_amount), 0) AS total_reservation_value,
        COUNT(DISTINCT m.maintenance_id) AS maintenance_tasks,
        COALESCE(SUM(m.cost), 0) AS total_maintenance_cost
    FROM EMPLOYEE e
    LEFT JOIN RESERVATION r ON e.employee_id = r.employee_id
    LEFT JOIN MAINTENANCE m ON e.employee_id = m.employee_id
    WHERE e.status = 'Active'
    GROUP BY e.employee_id, e.first_name, e.last_name, e.department, e.position
)
SELECT 
    employee_name,
    department,
    position,
    reservations_processed,
    maintenance_tasks,
    (reservations_processed + maintenance_tasks) AS total_activities,
    total_reservation_value,
    total_maintenance_cost,
    ROUND((total_reservation_value / NULLIF(reservations_processed, 0)), 2) AS avg_reservation_value,
    RANK() OVER (ORDER BY (reservations_processed + maintenance_tasks) DESC) AS productivity_rank
FROM EmployeeStats
ORDER BY total_activities DESC;

-- Query 20: Advanced correlated subquery to find most popular vehicle in each category
SELECT DISTINCT
    vc.category_name,
    v.vehicle_id,
    v.registration_number,
    v.make || ' ' || v.model AS vehicle,
    (
        SELECT COUNT(*)
        FROM RESERVATION r
        WHERE r.vehicle_id = v.vehicle_id
    ) AS rental_count,
    v.daily_rate
FROM VEHICLE v
JOIN VEHICLE_CATEGORY vc ON v.category_id = vc.category_id
WHERE (
    SELECT COUNT(*)
    FROM RESERVATION r
    WHERE r.vehicle_id = v.vehicle_id
) = (
    SELECT MAX(rental_count)
    FROM (
        SELECT COUNT(*) AS rental_count
        FROM RESERVATION r2
        JOIN VEHICLE v2 ON r2.vehicle_id = v2.vehicle_id
        WHERE v2.category_id = v.category_id
        GROUP BY r2.vehicle_id
    ) AS category_rentals
)
ORDER BY vc.category_name;